
public class Calculator extends javax.swing.JFrame {
private double firstNumber=0;
private double secondNumber=0;
private double result=0;
private String equalsOp;
private boolean calflag=false;
private static String operations;
private static boolean negativeFlag=false;
private static boolean firstNegativeFlag=false;
private static final double NEGATIVE=-1;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        window = new javax.swing.JTextField();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        subtractButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        decimalButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        equalsButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        negativeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator ");
        setResizable(false);

        window.setEditable(false);
        window.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        window.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        window.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowActionPerformed(evt);
            }
        });

        sevenButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        sevenButton.setText("7");
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });

        eightButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        eightButton.setText("8");
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });

        nineButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        nineButton.setText("9");
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });

        divideButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        divideButton.setText("<html>&divide;</html>");
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        fourButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        fourButton.setText("4");
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        fiveButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        fiveButton.setText("5");
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        sixButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        sixButton.setText("6");
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        multiplyButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        multiplyButton.setText("*");
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        oneButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        oneButton.setText("1");
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        twoButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        twoButton.setText("2");
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        threeButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        threeButton.setText("3");
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        subtractButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        subtractButton.setText("-");
        subtractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractButtonActionPerformed(evt);
            }
        });

        zeroButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        zeroButton.setText("0");
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        decimalButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        decimalButton.setText(".");
        decimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        addButton.setText("+");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        equalsButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        equalsButton.setText("=");
        equalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        clearButton.setText("C");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        backButton.setText("Backspace");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        negativeButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        negativeButton.setText("M");
        negativeButton.setToolTipText("This makes a digit in the display box negative");
        negativeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(window, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(subtractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(decimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(negativeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(window, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevenButton)
                    .addComponent(eightButton)
                    .addComponent(nineButton)
                    .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourButton)
                    .addComponent(fiveButton)
                    .addComponent(sixButton)
                    .addComponent(multiplyButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneButton)
                    .addComponent(twoButton)
                    .addComponent(threeButton)
                    .addComponent(subtractButton))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decimalButton)
                    .addComponent(zeroButton)
                    .addComponent(addButton)
                    .addComponent(equalsButton))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(backButton)
                    .addComponent(negativeButton))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void windowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_windowActionPerformed

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        window.setText(numberButton(window.getText(),5,operations));
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
        window.setText(numberButton(window.getText(),8,operations));
    }//GEN-LAST:event_eightButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
        window.setText(numberButton(window.getText(),7,operations));
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
        window.setText(numberButton(window.getText(),9,operations));
    }//GEN-LAST:event_nineButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        window.setText(numberButton(window.getText(),4,operations));
    }//GEN-LAST:event_fourButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        window.setText("");
        firstNumber=0;
        secondNumber=0;
        result=0;
        negativeFlag=false;
    }//GEN-LAST:event_clearButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        window.setText(numberButton(window.getText(),6,operations));
    }//GEN-LAST:event_sixButtonActionPerformed

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        window.setText(numberButton(window.getText(),1,operations));
    }//GEN-LAST:event_oneButtonActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        window.setText(numberButton(window.getText(),2,operations));
    }//GEN-LAST:event_twoButtonActionPerformed

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        window.setText(numberButton(window.getText(),3,operations));
    }//GEN-LAST:event_threeButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        window.setText(numberButton(window.getText(),0,operations));
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void decimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalButtonActionPerformed
        String enteredText=window.getText()+".";
        window.setText(enteredText);
    }//GEN-LAST:event_decimalButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if(!window.getText().isEmpty())
        {
            String enteredText=window.getText();
            window.setText(enteredText.substring(0,enteredText.length()-1));
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        operations="+";
        equalsOp="+";
        
        /*
        if(firstNumber!=0&&secondNumber!=0)
        {
            result=firstNumber+secondNumber;
            System.out.println("Triggered!");
            window.setText(""+result);
            firstNumber=0;
            secondNumber=0;
        }
        */
        
        if(firstNumber==0||result!=0)
        {
            firstNumber=Double.parseDouble(window.getText());
            window.setText(operations);
        }
        
        else
        {
            secondNumber=Double.parseDouble(window.getText());
            result=firstNumber+secondNumber;
            //System.out.println("Triggered!");
            window.setText(""+result);
            secondNumber=Double.parseDouble(window.getText());
        }
        //System.out.println("First Number: "+firstNumber);
        //System.out.println("Second Number: "+secondNumber);
    }//GEN-LAST:event_addButtonActionPerformed

    private void equalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButtonActionPerformed
        if(firstNumber!=0)
        {
            switch(equalsOp)
            {
                case "+":
                    if(result==0)
                    {
                        secondNumber=Double.parseDouble(window.getText());
                        result=firstNumber+secondNumber;
                        window.setText(""+result);
                    }
                    else
                    {
                        result=firstNumber+Double.parseDouble(window.getText());
                        secondNumber=0;
                        window.setText(""+result);
                    }
                    break;
                case "-":
                     if(result==0)
                    {
                        secondNumber=Double.parseDouble(window.getText());
                        result=firstNumber-secondNumber;
                        window.setText(""+result);
                    }
                    else
                    {
                        result=firstNumber-Double.parseDouble(window.getText());
                        secondNumber=0;
                        window.setText(""+result);
                    }
                    break;
                case "*":
                    if(result==0)
                    {
                        secondNumber=Double.parseDouble(window.getText());
                        result=firstNumber*secondNumber;
                        window.setText(""+result);
                    }
                    else
                    {
                        result=firstNumber*Double.parseDouble(window.getText());
                        secondNumber=0;
                        window.setText(""+result);
                    }
                    break;
                case "/":
                    if(result==0)
                    {
                        secondNumber=Double.parseDouble(window.getText());
                        result=firstNumber/secondNumber;
                        window.setText(""+result);
                    }
                    else
                    {
                        result=firstNumber/Double.parseDouble(window.getText());
                        secondNumber=0;
                        window.setText(""+result);
                    }
                    break;
                default:
            }
        }
    }//GEN-LAST:event_equalsButtonActionPerformed

    private void subtractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractButtonActionPerformed
         operations="-";
        equalsOp="-";
        
        /*
        if(firstNumber!=0&&secondNumber!=0)
        {
            result=firstNumber+secondNumber;
            System.out.println("Triggered!");
            window.setText(""+result);
            firstNumber=0;
            secondNumber=0;
        }
        */
        
        if(firstNumber==0||result!=0)
        {
            firstNumber=Double.parseDouble(window.getText());
            window.setText(operations);
        }
        
        else
        {
            secondNumber=Double.parseDouble(window.getText());
            result=firstNumber-secondNumber;
            //System.out.println("Triggered!");
            window.setText(""+result);
            secondNumber=Double.parseDouble(window.getText());
        }
        //System.out.println("First Number: "+firstNumber);
        //System.out.println("Second Number: "+secondNumber);
    }//GEN-LAST:event_subtractButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
        operations="*";
        equalsOp="*";
        
        /*
        if(firstNumber!=0&&secondNumber!=0)
        {
            result=firstNumber+secondNumber;
            System.out.println("Triggered!");
            window.setText(""+result);
            firstNumber=0;
            secondNumber=0;
        }
        */
        
        if(firstNumber==0||result!=0)
        {
            firstNumber=Double.parseDouble(window.getText());
            window.setText(operations);
        }
        
        else
        {
            secondNumber=Double.parseDouble(window.getText());
            result=firstNumber*secondNumber;
            //System.out.println("Triggered!");
            window.setText(""+result);
            secondNumber=Double.parseDouble(window.getText());
        }
        //System.out.println("First Number: "+firstNumber);
        //System.out.println("Second Number: "+secondNumber);
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void negativeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativeButtonActionPerformed

        /*
        if(window.getText().isEmpty()||negativeFlag==true)
        {
            if(negativeFlag==false)
            {
                negativeFlag=true;
                window.setText("-");
            }
            
            else
            {
                negativeFlag=false;
                window.setText("");
            }
        }
        else
        {
        */
            System.out.println("Occu");
            double oppNumber=NEGATIVE*Double.parseDouble(window.getText());
            System.out.println(oppNumber);
            window.setText(""+oppNumber);
        //}
    }//GEN-LAST:event_negativeButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        operations="/";
        equalsOp="/";
        
        /*
        if(firstNumber!=0&&secondNumber!=0)
        {
            result=firstNumber+secondNumber;
            System.out.println("Triggered!");
            window.setText(""+result);
            firstNumber=0;
            secondNumber=0;
        }
        */
        
        if(firstNumber==0||result!=0)
        {
            firstNumber=Double.parseDouble(window.getText());
            window.setText(operations);
        }
        
        else
        {
            secondNumber=Double.parseDouble(window.getText());
            result=firstNumber/secondNumber;
            //System.out.println("Triggered!");
            window.setText(""+result);
            secondNumber=Double.parseDouble(window.getText());
        }
        //System.out.println("First Number: "+firstNumber);
        //System.out.println("Second Number: "+secondNumber);
    }//GEN-LAST:event_divideButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    
    public static String numberButton(String text, int digit, String op)
    {
        
        String enteredText="";
        if(op=="")
        {
           enteredText=text+digit;
        }
        
        else
        {
            enteredText=""+digit;
            operations="";
        }
        return enteredText;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton decimalButton;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalsButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton negativeButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton subtractButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JTextField window;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
